### ISSUE TITLE
✨ `config.important`

### ISSUE THREAD

**Issue by 1aron** [master-co/css#131]
### Description

Make all CSS declarations add `!important`. This can be useful when using Master CSS with existing CSS that has high-specificity selectors.
```ts
export default {
    important: true
}
```
```css
.mt\:1 {
    margin-top: 0.0625rem !important
}

.text\:center {
    text-align: center !important
}

.hide {
    display: none !important
}

.full {
    width: 100% !important;
    height: 100% !important;
}
```
