### ISSUE TITLE
🐞 Declaring theme colors via the Group syntax with `classes` is invalid

### ISSUE THREAD

**Issue by 1aron** [master-co/css#138]
### What happened?

```ts
export default {
    themes: {
        light: {
            colors: {
                fader: 'slate-90'
            }
        },
        dark: {
            colors: {
                fader: 'gray-50'
            }
        }
    },
    classes: {
        'highlight-numbers': '{content:counter(lineNumber);inline-block;counter-increment:lineNumber;pr:16;text:right;ml:-5;fg:fader;w:30;font:80%}_.highlight-line:before'
    }
}
```
You can see the `fg:fader` declared in the group.

Unexpected CSS to be applied:
```css
.dark .\{content\:counter\(lineNumber\)\;inline-block\;counter-increment\:lineNumber\;pr\:16\;text\:right\;ml\:-5\;fg\:fader\;w\:30\;font\:80\%\}_\.highlight-line\:before .highlight-line:before,
.highlight-numbers .highlight-line:before {
    color: '#6b6a6d'
}
```

Expected CSS to be applied:
```css
.light .\{content\:counter\(lineNumber\)\;inline-block\;counter-increment\:lineNumber\;pr\:16\;text\:right\;ml\:-5\;fg\:fader\;w\:30\;font\:80\%\}_\.highlight-line\:before .highlight-line:before,
.light .highlight-numbers .highlight-line:before {
    color: '#a3abbf'
}
```

### Version

2.0.0-beta.101
