### ISSUE TITLE
✨ Hover and preview CSS rules with `config.classes`

### ISSUE THREAD

**Issue by 1aron** [master-co/css#160]
### Description

Here are the features currently supported by Master CSS Language Service:

<img width="681" alt="Screenshot 2023-02-03 at 6 19 26 PM" src="https://user-images.githubusercontent.com/33840671/216575176-2379d8e9-f7e2-4d39-b91e-54156160c3a3.png">

master.css.js
```ts
export const config = {
    classes: {
        btn: 'font:14 p:8|16'
    }
}
```
When you hover over the `btn` class in the markup:
```html
<a class="btn">
```
You can preview the CSS rules generated by `btn`:
```css
.btn, .font\:14 {
   font-size: 0.875rem
}

.btn, .p\:8\|16 {
   padding: 0.5rem 1rem
}
```
