### ISSUE TITLE
✨ `config.themeDriver`

### ISSUE THREAD

**Issue by 1aron** [master-co/css#177]
### Description

`class` ( Default )
```ts
export const config = {
    themeDriver: 'class'
}
```
```css
.dark .bg\:#000 { background-color: #000 }
```

`media`
```ts
export const config = {
    themeDriver: 'media'
}
```
```css
@media (prefers-color-scheme: dark) { .bg\:#000 { background-color: #000 } }
```
The `media` feature needs to verify whether the priority relationship between classes and media queries affects the order in which existing rules are applied.

`host`
```ts
export const config = {
    themeDriver: 'host'
}
```
```css
:host(.dark) .bg\:#000 { background-color: #000 }
```
