### ISSUE TITLE
🐞 `repeat()` accidentally converted units

### ISSUE THREAD

**Issue by 1aron** [master-co/css#195]
### Description

`grid-template-cols:repeat(2,auto)`

Incorrect:
```css
.grid-template-cols\:repeat\(2\,auto\) {
    grid-template-columns: repeat(0.125rem, auto)
}
```

Correct:
```css
.grid-template-cols\:repeat\(2\,auto\) {
    grid-template-columns: repeat(2, auto)
}
```

<img width="754" alt="Screenshot 2023-03-31 at 12 33 41 PM" src="https://user-images.githubusercontent.com/33840671/229023383-4599bb2e-5025-4a3d-a258-292eb73e1926.png">

### System Informations

macOS
