### ISSUE TITLE
🐞 `@media` and `@supports` doesn't transform `|` to ` `

### ISSUE THREAD

**Issue by 1aron** [master-co/css#198]
### Description

Incorrect and valid: `hidden@supports(transform-origin:5%_5%)`
Correct and invalid: `hidden@supports(transform-origin:5%|5%)`

### System Informations

macOS

**Comment by 1aron** [comment]
Released at [v2.0.0-beta.151](https://github.com/master-co/css/releases/tag/v2.0.0-beta.151)

**Comment by 1aron** [comment]
@BenSeage `pr:10@supports|selector(::-webkit-scrollbar)` doesn't work.

<img width="1111" alt="Screenshot 2023-05-24 at 4 53 05 PM" src="https://github.com/master-co/css/assets/33840671/31e5fa91-1508-408e-ae0d-27f904cf742e">

### Correct generated CSS

```css
@supports selector(::-webkit-scrollbar) {
    .pr\:10\@supports\|selector\(\:\:-webkit-scrollbar\) {
        padding-right: 0.625rem
    }
}
```
