### ISSUE TITLE
🐞 Theme colors are not mapped

### ISSUE THREAD

**Issue by 1aron** [master-co/css#199]
master.css.js
```ts
export const config {
    themes: {
        light: {
            colors: {
                primary: '#ebbb40'
            }
        },
        dark: {
            colors: {
                primary: '#fbe09d'
            }
        }
    },
}
```
HTML
```html
<div class="bg:linear-gradient(180deg,primary,gray-60)">
```
Generated CSS
```css
.bg\:linear-gradient\(180deg\,primary\,gray-60\) {
    background-image: linear-gradient(180deg, primary, #9e9da0)
}
```

---

We may need to verify several situations and suppose to apply: `bg:linear-gradient(180deg,primary,accent)`

### Situation 1
```ts
export const config = {
    themes: {
        light: { colors: { primary: '#000000', accent: '#111111' }  },
        dark: { colors: { primary: '#ffffff', accent: '#eeeeee' } }
    }
}
```
```css
.light .bg\:linear-gradient\(180deg\,primary\,accent\) { 
    background-image: linear-gradient(180deg, #000000, #111111)
}

.dark .bg\:linear-gradient\(180deg\,primary\,accent\) { 
    background-image: linear-gradient(180deg, #ffffff, #eeeeee)
}
```

### Situation 2
```ts
export const config = {
    themes: {
        light: { colors: { primary: '#000000' }  },
        dark: { colors: { primary: '#ffffff', accent: '#eeeeee' } }
    }
}
```
Ignore the rule `.light ...` if color is non-existent:
```css
.dark .bg\:linear-gradient\(180deg\,primary\,accent\) { 
    background-image: linear-gradient(180deg, #ffffff, #eeeeee)
}
```

### ~Situation 3~
```ts
export const config = {
    themes: {
        light: { colors: { primary: '#000000' }  },
        dark: { colors: { primary: '#ffffff' } }
    }
}
```
Ignore rules if color is non-existent:
```console
⚠️ `bg:linear-gradient(180deg,primary,accent)` doesn't generate any CSS rules
```

### Situation 4
```ts
export const config = {
    themes: {
        light: { colors: { primary: '#000000' }  },
        dark: { colors: { primary: '#ffffff' } }
    },
    colors: {
        accent: '#ff0000'
    }
}
```
```css
.light .bg\:linear-gradient\(180deg\,primary\,accent\) { 
    background-image: linear-gradient(180deg, #000000, #ff0000)
}

.dark .bg\:linear-gradient\(180deg\,primary\,accent\) { 
    background-image: linear-gradient(180deg, #ffffff, #ff0000)
}
```

### Situation 5
```ts
export const config = {
    themes: {
        light: { colors: { primary: '#000000' }  },
        dark: { colors: { primary: '#ffffff', accent: '#aa0000' } }
    },
    colors: {
        accent: '#ff0000'
    }
}
```
```css
.light .bg\:linear-gradient\(180deg\,primary\,accent\) { 
    background-image: linear-gradient(180deg, #000000, #ff0000)
}

.dark .bg\:linear-gradient\(180deg\,primary\,accent\) { 
    background-image: linear-gradient(180deg, #ffffff, #aa0000)
}
```

### Situation 6
Check the CSS rules generated by the group containing themes and other non-themes syntax:
```ts
export const config = {
    themes: {
        light: { colors: { fade: '#cccccc' } },
        dark: { colors: { fade: '#333333' } }
    }
}
```
```html
<div class="{block;fg:fade}_:where(p)_code:before"></div>
```
```css

.\{block\;fg\:fade\}_\:where\(p\)_code\:before :where(p) code:before {
    display: block;
}

.light .\{block\;fg\:fade\}_\:where\(p\)_code\:before :where(p) code:before {
    color: #cccccc;
}

.dark .\{block\;fg\:fade\}_\:where\(p\)_code\:before :where(p) code:before {
    color: #333333;
}
```
