### ISSUE TITLE
✨ `mcss-loader` for Webpack

### ISSUE THREAD

**Issue by 1aron** [master-co/css#204]
### Description

webpack.config.js
```css
module.exports = {
    module: {
        rules: [
            {
                test: /\.html$/i,
                loader: 'mcss-loader'
            },
        ],
    },
};
```
The loader scans your HTML like `index.html`, generates the corresponding CSS rules, and injects them with `<style id="master">`:
```diff
<html>
    <head>
+        <style id="master">.block{display:block}</style>
    </head>
    <body class="block"></body>
</html>
```
