### ISSUE TITLE
✨ Improve `overflow:overlay`

### ISSUE THREAD

**Issue by 1aron** [master-co/css#207]
### Description

Current:
```css
.overflow\:overlay {
    overflow: overlay;
}
```

Expect:
```css
.overflow\:overlay {
    overflow: auto; /* fallback */
    overflow: overlay;
}
```

`overflow` `overflow-x` `overflow-y`

https://caniuse.com/css-overflow-overlay
