### ISSUE TITLE
💖 Support BEM's double underscore naming

### ISSUE THREAD

**Issue by 1aron** [master-co/css#218]
**⚠️ It is not recommended to use the BEM naming style, the underscore is used as a descendant selector in Master CSS.**

### Description

In Master, underscores are used as stand-ins for descendant selectors, but we should avoid double underscores being converted to blanks.

```html
<div class="bg:red:hover_.feature__tab-title"></div>
```

### Current
```css
.bg\:red\:hover_\.feature__tab-title:hover .feature tab-title {
    background-color: rgb(209, 26, 30);
}
```

### Expect
```css
.bg\:red\:hover_\.feature__tab-title:hover .feature__tab-title {
    background-color: rgb(209, 26, 30);
}
```

**Comment by suasgn** [comment]
Perhaps it allows escaping an `_` underscore too?

```html
<div class="bg:red:hover_.my\_feature__tab-title"></div>
```

### Expect
```css
.bg\:red\:hover_\.my\_feature__tab-title:hover .my_feature__tab-title {
    background-color: rgb(209, 26, 30);
}
```
