### ISSUE TITLE
💖 `font-family` collide with predefined values

### ISSUE THREAD

**Issue by suasgn** [master-co/css#232]
### Description

Master CSS has three predefined values for the font-family rule:
```js
{
    mono: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace',
    sans: 'ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji',
    serif: 'ui-serif,Georgia,Cambria,Times New Roman,Times,serif'
}
```

A collision occurs when our arbitrary value contains the predefined value (case-sensitive).

```html
<div class="
        font-family:'Noto\|Sans'
        font-family:Noto|Sans
        font-family:Open,sans
    ">
        OK
</div>
<div class="
        font-family:'Open|Sans'
        font-family:Open|sans
    ">
        NOT OK
</div>
```

```css
/* OK */

.font-family\:Noto\|Sans {
    font-family: "Noto Sans";
}

.font-family\:\'Noto\\\|Sans\' {
    font-family: "Open|Sans";
}

/* OK, a predefined value can be used to define a fallback only if a comma separates it. */
.font-family\:Open\,sans {
    font-family: Open, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}

/* NOT OK */

.font-family\:Open\|sans {
    font-family: "Open ui-sans-serif", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}

.font-family\:\'Open\|Sans\' {
    font-family: "Open|Sans";
}
```
