### ISSUE TITLE
💖 Deprecate `sm:`, `sp:` collision-prone syntax

### ISSUE THREAD

**Issue by 1aron** [master-co/css#256]
### Description

It is easy to conflict with existing CSS frameworks:
```css
.sm\:px-6 {
    scroll-margin: px-6
}

.sm\:h-34 {
    scroll-margin: h-34
}

.sm\:flex-row {
    scroll-margin: flex-row
}
```

### Expect
```html
<div class="scroll-m:20 scroll-mx:32 scroll-p:16 scroll-px:48">
```
