### ISSUE TITLE
🐞 Colors with themes are not reflected in the classes

### ISSUE THREAD

**Issue by 1aron** [master-co/css#260]
### Description

```html
<button class="btn"></button>
```
```js
/** @type {import('@master/css').Config} */
export default {
    colors: {
        primary: {
            filled: {
                "@light": "gold-75",
                "@dark": "gold-70"
            }
        }
    },
    classes: {
        btn: 'bg:primary-filled'
    }
}
```

## Current
```css
/* Generated CSS */

.light .bg\:primary-filled {
    background-color: rgb(236, 187, 64);
}

.dark .bg\:primary-filled {
    background-color: rgb(220, 160, 0);
}
```

## Expect
```css
/* Generated CSS */

.light .bg\:primary-filled,
.light .btn {
    background-color: rgb(236, 187, 64);
}

.dark .bg\:primary-filled,
.dark .btn {
    background-color: rgb(220, 160, 0);
}
```
