### ISSUE TITLE
Cannot parse `content` with `\'` string

### ISSUE THREAD

**Issue by serkodev** [master-co/css#27]
### Description

Unexpected result when parsing `\'` in `content`

## Case 1

```html
<div class="content:'foo\'s'"></div>
```

Expected
```css
.content\:\'foo\\\'s\' {
    content:"foo's";
}
```

Current Result
```css
.content\:\'foo\\\'s\' {
    content: "foo' s";
}
```

## Case 2

```html
<div class="content:'foo\'s':after"></div>
```

Expected
```css
.content\:\'foo\\\'s\'\:after {
    content:"foo's";
}
```

Current Result
```css
.content\:\'foo\\\'s\'\:after {
}
```

### System Informations

All platforms
