### ISSUE TITLE
💖 Make CSS variable syntax support color tokens

### ISSUE THREAD

**Issue by 1aron** [master-co/css#276]
### Description

```html
<div class="$primary:blue-60">
```
Generated CSS:
```css
.\$primary\:blue-60 {
    --primary: #6b9ef1;
}
```
