### ISSUE TITLE
🐞 CSS variables with `themeDriver: 'media'` were not captured

### ISSUE THREAD

**Issue by 1aron** [master-co/css#301]
- #283 

`<style id="master">` with `themeDriver: 'media'`
```css
:root {
    --primary: '#ff0000'
}

@media (prefers-color-scheme: 'dark') {
    :root { --primary: #000000 }
}

@media (prefers-color-scheme: 'light') {
    :root { --primary: #ffffff }
}
```

## Expected
`css.variables`
```js
{
    primary: {
        type: 'color',
        space: 'rgb',
        value: '255 0 0',
        themes: {
            dark: { type: 'color', space: 'rgb', value: '0 0 0' },
            light: { type: 'color', space: 'rgb', value: '255 255 255' },
        },
        natives: [...],
        ...
    }
}
```
@BenSeage Also, I think `native` should be attached to a theme or a single variable:
```js
{
    primary: {
        type: 'color',
        space: 'rgb',
        value: '255 0 0',
        themes: {
            dark: { type: 'color', native: ..., space: 'rgb', value: '0 0 0' },
            light: { type: 'color', native: ..., space: 'rgb', value: '255 255 255' },
        },
        native: ...
        ...
    }
}
```
@BenSeage Don’t forget to review the processing of Progressive Rendering related logic and add tests.

## Received
Not caught.
