### ISSUE TITLE
💖 Reset outline style on focus to maintain accessibility

### ISSUE THREAD

**Issue by 1aron** [master-co/css#302]
The default outline styles for most elements:

![image](https://github.com/master-co/css/assets/33840671/ff2c8e76-75f2-4a7a-8a1f-b4ce5a29cc4b)

If we could make sure that the above is the default behavior of all elements, then just reset focus outline again in  **@master/normal.css**:
```css
*,
::before,
::after {
    border: 0 solid;
    outline: 0 solid;
}

:focus-visible {
    outline: -webkit-focus-ring-color auto 1px;
}
```

_Originally posted by @1aron in https://github.com/master-co/css/issues/299#issuecomment-1793493602_

**Comment by lesha1201** [comment]
@1aron 

**Browsers default  styles:**

- WebKit - https://searchfox.org/wubkat/source/Source/WebCore/css/html.css#1292-1298
- Chromium - https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/resources/html.css;l=1220;bpv=0
- Firefox - https://searchfox.org/mozilla-central/source/layout/style/res/ua.css#176

You can search for `outline` there to see how it might affect.

From my research, those 3 browsers have different styling for the default focus state. To use the default styling, we can do something like this:

```css
:focus-visible {
    outline: auto;
}
```

Chromium and Firefox has some special cases where `outline` is also used but I'm not sure if they actually matter in our case. For example, Chromium has:

```css
input[type="time" i]::-webkit-calendar-picker-indicator:focus-visible {
  outline: solid 2px -webkit-focus-ring-color;
  outline-offset: -2px;
}
```

But it doesn't apply it to anything when I tested in Chrome 119 because `-webkit-calendar-picker-indicator` isn't focusable at all. However, I'm not sure about those special cases because I don't have any context about them.

![image](https://github.com/master-co/css/assets/10157660/4b827457-d274-4b99-b510-85014f07fdb6)
