### ISSUE TITLE
💖 Create `CSSStyleRule` based on different themes

### ISSUE THREAD

**Issue by 1aron** [master-co/css#303]
- #301 

### Current

```js
export default {
    variables: {
        primary: { '@light': '#ffffff', '@dark': '#000000' },
        secondary: { '@light': '#000000', '@dark': '#ffffff' }
    }
}
```
```html
<div class="bg:primary fg:secondary">...
```
Generated CSS
```css
.light { --primary: 255 255 255 }
.light { --secondary: 0 0 0 }
.dark { --primary: 0 0 0 }
.dark { --secondary: 255 255 255 }
```

### Expected

Generated CSS
```css
.light { --primary: 255 255 255; --secondary: 0 0 0 }
.dark { --primary: 0 0 0; --secondary: 255 255 255 }
```
- [x] We should manipulate the [CSSStyleDeclaration](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration) to add or remove CSS variables instead of accessing and parsing CSS text.
  - [CSSStyleDeclaration.setProperty()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty)
  - [CSSStyleDeclaration.removeProperty()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/removeProperty)
  - [CSSStyleDeclaration.getPropertyValue()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue)
- [ ] Replace `.light` with `.\@dark` to make class selectors starting with `@` fixed to theme-specific CSSRule.
