### ISSUE TITLE
💖 Prefer animation names over variables

### ISSUE THREAD

**Issue by 1aron** [master-co/css#317]
### Current

```ts
export default {
    variables: {
        float: '#000000'
    },
    animations: {
        float: {
            '0%': { transform: 'none' },
            '50%': { transform: 'translateY(-1.25rem)' },
            to: { transform: 'none' }
        },
    }
}
```
```html
<div class="@float|.5s">
```
Generated CSS:
```css
...
.\@float\|\.5s {
    animation: #000000 .5s;
}
```

### Expected

```ts
export default {
    variables: {
        float: '#000000'
    },
    animations: {
        float: {
            '0%': { transform: 'none' },
            '50%': { transform: 'translateY(-1.25rem)' },
            to: { transform: 'none' }
        },
    }
}
```
```html
<div class="@float|.5s">
```
Generated CSS:
```css
...
.\@float\|\.5s {
    animation: float .5s;
}
```
Related properties: `animation` and `animation-name`
