### ISSUE TITLE
✨ `@supported` shorthand for whether declarations are supported

### ISSUE THREAD

**Issue by 1aron** [master-co/css#320]
## Case 1
```diff
- grid@supports(display:grid)
+ grid@supported
```
```css
@supports (display:grid) {
    .grid\@supported {
        display: grid
    }
}
```

## Case 2
```diff
- {grid;w:100dvw}@supports(display:grid)and(width:100dvw)
+ {grid;w:100dvw}@supported
```
```css
@supports (display:grid) and (width:100dvw) {
    .\{grid\;w\:100dvw\}\@supported {
        display: grid;
        width: 100dvw;
    }
}
```
