### ISSUE TITLE
✨ Container Queries

### ISSUE THREAD

**Issue by 1aron** [master-co/css#334]
### Description

- #43 
- https://developer.mozilla.org/en-US/docs/Web/CSS/@container

Too many people have asked about this feature, and here is the proposal of **Master CSS 2.X Container Queries**.

## Applying styles based on a container's size
```html
<div class="container:inline-size">
    <div class="font:32@container<=600">
        <h2>Card title</h2>
        <p>Card content</p>
    </div>
</div>
```
Generated CSS
```css
.container\:inline-size {
    container-type: inline-size
}

@container (max-width: 600px) {
    .font\:32\@container\<\=600 {
        font-size: 2rem
    }
}
```

## Creating named container contexts
We intend to fallback any unknown at tokens to container names.
```html
<div class="container:post/inline-size">
    <div class="font:32@post<=600">
        <h2>Card title</h2>
        <p>Card content</p>
    </div>
</div>
```
Generated CSS
```css
.container\:post\/inline-size {
    container: post / inline-size
}

@container post (max-width: 600px) {
    .font\:32\@post\<\=600 {
        font-size: 2rem
    }
}
```
