### ISSUE TITLE
🐞 clamp() function does not work correctly

### ISSUE THREAD

**Issue by rundezv** [master-co/css#358]
### Description

If specified normally, an empty style is generated.

```html
<p class="font-size:clamp(1.5rem,2vw+1rem,2.25rem)">...</p>
```
```css
.font-size\:clamp\(1\.5rem\,2vw\+1rem\,2\.25rem\) {}
```

When I wrap it with the calc() function, it works fine.

```html
<p class="font-size:clamp(1.5rem,calc(2vw+1rem),2.25rem)">...</p>
```
```css
.font-size\:clamp\(1\.5rem\,calc\(2vw\+1rem\)\,2\.25rem\) {
  font-size: clamp(1.5rem, 1rem + 2vw, 2.25rem);
}
```
