### ISSUE TITLE
Multiplier unit (x) doesn't work with scope variables

### ISSUE THREAD

**Issue by ethylon** [master-co/css#399]
### Description

I'm trying to define a scope variable with `$padding-l:1.5x` and using it with `pl:$(padding-l)`.
I think it's trying to convert the x modifier to px but fails? As this class results in `6` instead of `6px`.

Even if it did succeed, converting to rem would be better, just like `pl:1.5x` translates to `padding-left: 0.375rem`.

# Expected result:
```css
.\$padding-l\:1\.5x {
  --padding-l: 0.375rem;
}
```

# Actual result:
```css
.\$padding-l\:1\.5x {
  --padding-l: 6;
}
```

Thanks, love this framework! 

### Reproduction

https://rc.css.master.co/play/a8k0crrvruyk

### System Informations

Master CSS version: v2.0.0-rc.63
