### ISSUE TITLE
Consider using `$var` instead of $(var) for access

### ISSUE THREAD

**Issue by 1aron** [master-co/css#401]
### Context

In Sass, we use variables like this:
```scss
$a: #000;
$b: $a;

a {
  color: $a;
  border-color: $b;
}
```
Compiled:
```css
a {
  color: #000;
  border-color: #000;
}
```

### Current

```js
export default {
    variables: {
        a: '#000000',
        b: '$(a)',
        c: '$(a)/.5'
    }
}
```
```html
<div class="fg:a">
<div class="fg:$(a)">
```

### Expected

```js
export default {
    variables: {
        a: '#000000',
        b: '$a',
        c: '$a/.5'
    }
}
```
```html
<div class="fg:a">
<div class="fg:$a">
```
Follow Sass's approach to reduce the learning curve and make it more concise.

You can still use `$(var)` to resolve specific conflicts. For example, `a-b` variable:
```html
<div class="m:calc($a-b-3)">invalid</div>
<div class="m:calc($(a-b)-3)">valid</div>
```
