### ISSUE TITLE
Apply multiple font properties with the same name

### ISSUE THREAD

**Issue by ceopaludetto** [master-co/css#402]
### Description

In tailwindcss@v3 it is possbile to configure fonts in this way:

```ts
theme: {
  fontFamily: {
    sans: ["Inter"]
  },
  fontSize: {
    "label-large": [14, { fontWeight: 500, letterSpacing: 0.5, lineHeight: 20 }]
  }
}
```

Which roughly generates the following:

```html
<p class="text-label-large">Hi</p>
```
```css
.text-label-large {
  font-family: Inter;
  font-size: 14px;
  font-weight: 500;
  letter-spacing: 0.5;
  line-height: 20;
}
```

So I tried to do the same in @master/css@v2 with the following:

```ts
variables: {
  "font-family": {
    test: ["arial", "sans-serif"],
  },
  "font-weight": {
    test: 500,
  },
  "font-size": {
    test: 20,
  },
  "line-height": {
    test: 1.5,
  },
}
```

But due to name collision, only font-weight is applied:

```html
<p class="font:test">Hi</p>
```
```css
.font\:test {
  font-weight: 500;
}
```

It is possible to achieve the same functionality? This can be really useful to implement [material 3](https://m3.material.io/styles/typography/type-scale-tokens#40fc37f8-3269-4aa3-9f28-c6113079ac5d) typography scale system

**Comment by 1aron** [comment]
@ceopaludetto This is expected. In Master CSS, we deliberately map certain CSS properties ambiguously to a shared variable namespace in order to simplify the markup. https://github.com/master-co/css/blob/rc/packages/core/src/config/rules.ts#L192-L199

Therefore, if a collision occurs, you should write out the full variable name.
```ts
<div class="font-weight:font-weight-test">
```
However, this is admittedly a somewhat awkward behavior, and we will further evaluate how to improve it.

Alternatively, what we might need is a warning to alert developers when a collision occurs.

**Comment by ceopaludetto** [comment]
I was able to achieve what I want by creating a new rule:
```ts
rules: {
  typography: {
    subkey: "typ",
    declare(value) {
      if (!this.css.variables.has(`font-size-${value}`))
        return {};
          
      return {
        "font-family": this.css.variables.get(`font-family-sans`)!.value.toString(),
        "font-size": toRem(this.css.variables.get(`font-size-${value}`)!.value),
        "font-weight": this.css.variables.get(`font-weight-${value}`)!.value,
        "line-height": toRem(this.css.variables.get(`line-height-${value}`)!.value),
        "letter-spacing": toRem(this.css.variables.get(`letter-spacing-${value}`)!.value),
      };
    },
  },
},
```

Then I just use like this:

```html
<p class="typ:test">Hi</p>
```

Which generates:
```css
.typ\:test{
  font-family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;
  font-size: 1.25rem;
  font-weight: 500;
  line-height: 1.25rem;
  letter-spacing: 0.03125rem;
}
```
