### ISSUE TITLE
CSS Normalize/Reset Rules Override Master CSS Runtime Styles

### ISSUE THREAD

**Issue by adonig** [master-co/css#403]
## Summary

CSS normalize/reset rules are taking precedence over Master CSS runtime-generated styles, causing utility classes to be ineffective.

## Problem Description

When using Master CSS utility classes, normalize/reset CSS rules override the generated styles, making utilities appear broken or ineffective.

### Example Issue

**CSS Reset/Normalize (higher priority):**
```css
button, input, optgroup, select, textarea {
    color: inherit;
    background-color: #0000;
    margin: 0;
    padding: 0;
    font-family: inherit;
    font-size: 100%;
}
```

**Master CSS Generated (lower priority):**
```css
.btn-primary {
    background-color: rgb(26, 26, 26);
}
```

**Result:** The `btn-primary` class has no visible effect.

### Reproduction

1. Clone [this repository](https://github.com/adonig/playground-master-css)
2. `pnpm install`
3. `pnpm run dev` and see the styled button
4. Edit `vite.config.ts` and remove `{injectNormalCSS: false}`
5. `pnpm run dev` and see the broken button

### System Informations

- **Master CSS Version**: v2.0.0-rc.68
- **Framework**: Vite + React
- **Browser**: Brave 1.79.126 (Official Build) (64-bit), Chromium: 137.0.7151.119
- **Node**: 22.16.0
- **OS**: Fedora Linux Workstation 42
