### ISSUE TITLE
✨ Support for container query/units and :has pseudo class

### ISSUE THREAD

**Issue by bhvngt** [master-co/css#43]
### Description

Given that the support for :has pseudo class and container queries is becoming main stream with the release of [chrome 105](https://chromestatus.com/roadmap) (safari 15.4 already has support for :has and Safari 16 will have support for container queries). 

Is there any plan to support them?

**Comment by 1Aron** [comment]
@bhvngt MasterCSS is an new CSS language so you can use all native CSS features.
# `:has()`
You can now use `:has()`: 
```html
<form class="outline:5:has(:focus)">
    <input/>
    ...
</form>
```

# Related container properties
For unsupported CSS properties you can first use the group/property syntax `{}`
```html
<sidebar class="{container-type:inline-size}">
```
We haven't yet designed a syntax for `@container`, we have to make sure that it is suitable to be defined by class, like `@keyframes` We don't support it, because we prefer you to define it directly through the traditional way.
```css
.sidebar {
  container-type: inline-size;
  container-name: sidebar;
}

@container sidebar (min-width: 400px){
  .card {
    display: grid;
    grid-template-columns: 2fr 1fr;
  }
}
```
https://caniuse.com/css-container-queries
